# Generated by Django 3.2.9 on 2021-12-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airquality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('o3', models.FloatField()),
                ('no2', models.FloatField()),
                ('so2', models.FloatField()),
                ('co', models.FloatField()),
            ],
        ),
    ]
