# Generated by Django 3.2.9 on 2021-12-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airquality',
            name='co',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='no2',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='o3',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='so2',
        ),
    ]
